name: "MiniProject 2"
description: "Beginner heaven"
google: "151496322-1"
resume: "https://docs.google.com/document/d/e/2PACX-1vSOVsOHnv0tWpmUTQFA1LfpaGrpVShPPij5CmLdY9BOiHotXAF6UXKco2-KDv0JftEKbAivTBB_us6B/pub?embedded=true"
Project_1: "https://github.com/danilo-patrucco/Mini_Project_1_IS117"
Project_2: "https://github.com/danilo-patrucco/miniproject2"
Project_3: ""
Project_4: ""
first_name: "Danilo Patrucco"

url: '' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

